### ISSUE TITLE
Shorthand properties

### ISSUE THREAD

**Issue by ghost** [csstools/stylelint-use-logical#29]
Currently (if I'm not mistaken) the plugin does not deal with shorthand properties like `margin`, `padding`, etc. In looking at the spec: https://www.w3.org/TR/css-logical-1/#logical-shorthand-keyword, it looks like this is still under discussion, so that's not surprising.

I was wondering what the opinions are on how to best deal with this. Would it be too invasive to do this for example, when autofixing with this plugin:

```css
/* from this */
blockquote {
  margin: 1em 2em 3em 4em;
}

/* to this */
blockquote {
  margin-block-start:  1em;
  margin-inline-start: 2em;
  margin-block-end:    3em;
  margin-inline-end:   4em;
}
```

I suppose one could also outlaw the usage of shorthand via other rules, but was just curious on the recommended course of action.
