### ISSUE TITLE
Except doesn't work as expected

### ISSUE THREAD

**Issue by yepninja** [csstools/stylelint-use-logical#3]
### Version of stylelint-use-logical
`1.1.0`
### Config
```js
module.exports = {
	plugins: [
		'stylelint-use-logical',
	],
	rules: {
		'csstools/use-logical': ['always', {
			except: [
				'top',
				'left',
			],
		}],
	},
}
```

### Code
```css
/* index.css */
.selector {
	position: absolute;
	top: -4px;
	left: 0;
}
```

### Error

> index.css
 11:2  ✖  Unexpected top property. Use inset-start.   csstools/use-logical

### Expected
No error because `top` property is added to the `expect` array.
