### ISSUE TITLE
Autofix loses !important declarations

### ISSUE THREAD

**Issue by ktym4a** [csstools/stylelint-use-logical#36]
When autofixing physical properties to logical properties, the plugin incorrectly handles `!important` declarations.

## Input CSS
```css
body { left: 0; right: 0 !important; }
```

## Current output
```css
body { inset-inline: 0; }
```

## Expected output
```css
body { inset-inline-start: 0; inset-inline-end: 0 !important; }
```

The autofix should preserve the `!important` declaration. When properties have different importance levels, they should not be merged into shorthand properties.
